#Maven 阿里云镜像
before_script:
  - rm -rf /root/.m2/settings.xml
  - echo -e "<?xml version=\""1.0\"" encoding=\""UTF-8\""?><settings xmlns=\""http://maven.apache.org/SETTINGS/1.0.0\"" xmlns:xsi=\""http://www.w3.org/2001/XMLSchema-instance\"" xsi:schemaLocation=\""http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd\""><mirrors><mirror><id>alimaven</id><name>aliyun maven</name><url>http://maven.aliyun.com/nexus/content/groups/public/</url><mirrorOf>central</mirrorOf></mirror></mirrors></settings>" > /root/.m2/settings.xml

# 定义 stages
stages:
  - test
  - build

# 定义 jobs
test app:
  stage: test
  script:
    - echo "I am test job"
    - mvn test

# 定义 job
build app:
  stage: build
  tags:
    - dockersock
  script:
    - mvn  -Dmaven.test.skip=true clean package docker:build